import type { Metadata } from 'next'
import './globals.css'
import localFont  from 'next/font/local'

const myFont = localFont({
  src : './OpenDyslexic-Regular.otf',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${myFont.className} font-sans`}>{children}</body>
    </html>
  )
}
